language: ruby
rvm:
  - 2.5.3

# Grant Travis execute permissions for script
before_script:
 - chmod +x ./script/cibuild

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - release

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false